version: "3"
services:
  web:
    environment:
    - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    - RAILS_SERVE_STATIC_FILES=true  # serve static files in production environment for standalone use
    build: .
    command: bin/init
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    restart: unless-stopped

