# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625f51cf376ab7a5584be205d8f3db66d9d20d202a675d003b10bda2dd0ae4d75bdce97a79a76112f570b6a69f187ad3094ebd2845ddfab063edf5131caa8742

test:
  secret_key_base: aff71f98615e047ffae9b9cc45bf221fe434535f77d74cc03686d7614163e9105303c3ad4985b369bc40c127938da0b13a292d9dd2ef79f82480daa74b0a3c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
